# NumPy
Numpy stands for Numerical Python. It is a Python library used for Scientific Computing.

# Why Numpy?
1. Allows several mathematical operations
2. Faster operations

In [1]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

np_array = np.array(list1)
print(np_array)
type(np_array)

# Numpy Array Dimensions

1D Array: a1 = [1, 2, 3] a1[0]
2D Array: a2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]  a2[][]                ]
3D Array: a3 = [
            [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
            [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  a3[][][]
            [[19, 20, 21], [22, 23, 24], [25, 26, 27]],
]

# CREATING A 1D ARRAY

In [9]:
a = np.array([1, 2, 3, 4])
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [10]:
# Get the number of rows/columns
a.shape

(4,)

In [11]:
# Number of dimensions
a.ndim

1

In [12]:
a.dtype

dtype('int64')

# 2D NumPy Array

In [33]:
b = np.array(((1, 2, 3, 4), (5, 6, 7, 8)))
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [34]:
b.shape

(2, 4)

In [17]:
b.ndim

2

In [18]:
b.dtype

dtype('int64')

# Specifying the Data Type

In [20]:
c = np.array([1, 2, 3, 4], dtype=float)
print(c)

[1. 2. 3. 4.]


In [21]:
c.dtype

dtype('float64')

In [22]:
z = np.array((1, 2, 4)).astype(float)
print(z)

[1. 2. 4.]


# PLACE HOLDERS IN NUMPY ARRAYS

In [23]:
# Create an array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
# Create an array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
# Create an array of specific value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [26]:
# Create an Identity Matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
# Create random numbers between 0-1
b = np.random.random((3,4))
print(b)

[[0.43019148 0.48283495 0.98760689 0.80920708]
 [0.12198706 0.73133834 0.08415994 0.56420313]
 [0.20916896 0.32263983 0.92582748 0.33559303]]


In [46]:
# Create Random Integer Values
c = np.random.randint(10, 100, (3,5)) # start, stop, (r, c)
print(c)

[[28 33 83 29 41]
 [82 77 38 39 24]
 [75 22 26 43 89]]


In [32]:
# Create a numpy array of evenly spaced values
d = np.linspace(10, 30, 5)
print(d)

[10. 15. 20. 25. 30.]
